# docker-compose.yml
version:                   "3"
services:
  client:
    build:                 ./server
    restart:               always
    ports:
        - "3000:3000"
    volumes:
        - ./client:/client
        - /client/node_modules
    links:
        - server
  server:
    build:                 ./server
    restart:               always
    ports:
        - "8000:8000"
    volumes:
        - ./server:/server
        - /server/node_modules
