# docker-compose.yml
version:            "3"
services:
  client:
    build:          ./client
    restart:        always
    container_name: client
    ports:
        - "3000:3000"
    volumes:
        - ./client:/client
        - /client/node_modules
    links:
        - server
  server:
    build:          ./server
    restart:        always
    container_name: server
    ports:
        - "8000:8000"
    volumes:
        - ./server:/server
        - /server/node_modules
  redis:
    image:          redis
    restart:        always
    container_name: redis
    ports:
        - "6379:6379"
  analysis:
    build:          ./analysis
    restart:        always
    container_name: analysis
